MACHINE = "hyper-host-arm64"
DISTRO = "poky-tiny"
PREFERRED_PROVIDER_virtual/kernel:hyper-host-arm64 = "linux-host-tiny"
PREFERRED_VERSION_linux-host-tiny:hyper-host-arm64 = "7.2%"
PREFERRED_VERSION_virtual/kernel:hyper-host-arm64 = "7.2%"
TMPDIR .= "-${BB_CURRENT_MC}"
HOST_SWAP_FEATURE = "zswap.scc"
