require conf/distro/poky.conf

DISTRO = "kvm-distro"
DISTRO_NAME = "KVM Distro"

# Enable KVM hypervisor capabilities in the kernel
DISTRO_FEATURES:append = " virtualization kvm"

# Spawn login prompts for both QEMU (ttyAMA0) and Kvmtool (ttyS0)
SERIAL_CONSOLES = "115200;ttyAMA0 115200;ttyS0"

PREFERRED_PROVIDER_virtual/kernel = "linux-yocto-tiny"
